SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (SELECT PARENT_ITEM_ID
                    FROM ITEM_TREE
                    WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_ID DESC;

/* NOT EXISTS 사용
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
WHERE NOT EXISTS (
    SELECT PARENT_ITEM_ID
    FROM ITEM_TREE T
    WHERE T.PARENT_ITEM_ID = I.ITEM_ID
)
ORDER BY I.ITEM_ID DESC;
*/
