WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT D.ID, D.PARENT_ID, GENERATION + 1
    FROM ECOLI_DATA D JOIN CTE C ON D.PARENT_ID = C.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM CTE C LEFT JOIN ECOLI_DATA D ON C.ID = D.PARENT_ID
WHERE D.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION ASC;